npc:
  can-change-visibility: false

  bypass-antibot-data: true
  bypass-antibot-remove: true
  bypass-antibot-radius: true

punishments:
  punishment-enabled: true
  punishment-command: 'kick %player% &3Unfair Advantage?'
  punishment-max-vl: 40

  broadcast-message-enabled: false
  broadcast-message: '&b&lVigilAC &7> &3%player% &7- Unfair Advantage.\n'

alerts:
  vl-to-first-alert: 10
  vl-to-next-alert: 3